```{r}
library("dplyr")
library("ggplot2")
library("corrplot")

df <- read.csv2(
  file = "C:\\Users\\maxim\\Desktop\\Fallstudien\\FS1\\Data\\Happiness.csv",
  na.strings = c("", "NA"),
  fileEncoding = "UTF-8",   
  check.names = FALSE       
)

sum(is.na(df))

```

```{r}
# Welche L¨ander haben den h¨ochsten/niedrigsten Gesamtscore und eignen sich deswegen besonders
# als neue Heimat bzw. sind eher auszuschließen? Welche Faktoren haben die st¨arkste Verbindung
# mit dem Gesamtscore?

names(df) <- gsub(" ", "_", names(df))

means <- df %>% select(-Year) %>% group_by(Country_name) %>% summarise(across(where(is.numeric), mean, na.rm = TRUE))

# Durchschnitt über die Jahre 

means

worst <- means[order(means$Life_Ladder),][1:5,]

best <- means[order(means$Life_Ladder, decreasing = TRUE),][1:5,]

best_worst <- rbind(best, worst)

# Grafiken im Mittel
ggplot(best_worst, aes(x = reorder(Country_name, Life_Ladder),
                       y = Life_Ladder,
                       fill = Life_Ladder)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "tomato", high = "darkgreen", guide = "none") +  
  geom_text(aes(label = round(Life_Ladder, 2)),                            
            vjust = -0.3, size = 3.5) +
  labs(x = "Countries",
       y = "Life Ladder Score",
       title = "Worst/Best five Countries in Happiness Score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim = c(0,max(best_worst$Life_Ladder)*1.1))

# Zeitlicher Verlauf

time <- df[df$Country_name %in% c("South Sudan", "Togo", "Central African Republic", "Burundi", "Rwanda", "Netherlands", "Switzerland", "Norway", "Finland", "Denmark"),]

time$Country_name <- factor(
  time$Country_name,
  levels = c("Finland", "Denmark", "Norway", "Switzerland", "Netherlands",
             "Rwanda", "Burundi", "Togo", "Central African Republic", "South Sudan")
)

time$col <- ifelse(time$Country_name %in% c("Netherlands", "Switzerland", "Norway", "Finland", "Denmark"),"Good_Score","Bad_Score")

ggplot(time, aes(x = Year, y = Life_Ladder, group = Country_name, color = col))+geom_line()+ geom_point()+theme_minimal()+
  labs(x = "Time Span", y = "Life Ladder Score", title = "Chronological Sequence of Ladder Score")+
  # scale_x_continuous(breaks = sort(unique(time$Year)))+
  scale_color_manual(values = c("Good_Score" = "darkgreen", "Bad_Score" = "tomato"))+
  facet_wrap(~Country_name, scales = "fixed", ncol = 5)

# Abweichungen innerhalb der guten Länder
sd(df[df$Country_name %in% c("Netherlands", "Switzerland", "Norway", "Finland", "Denmark"),]$Life_Ladder)

# Abweichung innerhalb der schlechten Länder
sd(df[df$Country_name %in% c("South Sudan", "Togo", "Central African Republic", "Burundi", "Rwanda"),]$Life_Ladder)

```

```{r}
#### Kovarianzstruktur 

cov(means[sapply(means, is.numeric)])

# corrplot(cov(means[sapply(means, is.numeric)]), method = "color", type = "upper")

num_df <- means[sapply(means, is.numeric)]

sum(is.na(num_df))

corrplot(cor(na.omit(num_df), use = "pairwise.complete.obs"), 
         method = "color", type = "upper")

  
num_cols <- df[sapply(df, is.numeric)]


cor(num_cols, use = "pairwise.complete.obs")["Life_Ladder", ]

cov_df <- as.data.frame(t(cor(num_cols, use = "pairwise.complete.obs")["Life_Ladder", ]))


cor_df <- data.frame(
  Variable = names(cov_df),
  Correlation = as.numeric(cov_df)
)

# Barplot
ggplot(cor_df, aes(x = reorder(Variable, Correlation), y = Correlation, fill = Correlation)) +
  geom_bar(stat = "identity", na.rm = TRUE) +
  coord_flip() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(title = "Variable Correlation with Life Ladder Score",
       x = "Variable", y = "Correlation") +
  theme_minimal() +
  theme(axis.text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))

```

```{r}
#PCA für die Grafik
prcomp(na.omit(num_cols), scale. = TRUE)
#Sehr viele NA deswegen Spalten entfernen wo sehr viele NA sind 

num_cols_wo_NA <- df %>%
  select(where(is.numeric)) %>%
  select(where(~ mean(!is.na(.)) > 0.8))

summary(prcomp(na.omit(num_cols_wo_NA), scale. = TRUE))

PCS <- prcomp(na.omit(num_cols_wo_NA), scale. = TRUE)$rotation

summary(prcomp(na.omit(num_cols_wo_NA), scale. = TRUE))$importance

var_influence <- rowSums(PCS[, 1:3]^2)
importance_df <- data.frame(
  Variable = names(var_influence),
  Importance = as.numeric(var_influence),
  row.names = NULL
)

importance_df <- importance_df[, !names(importance_df) %in% c("Year", "Life_Ladder")]
top10 <- importance_df[order(-importance_df$Importance), ][1:10, ]$Variable


ggplot(cor_df[cor_df$Variable %in% top10,], aes(x = reorder(Variable, Correlation), y = Correlation, fill = Correlation)) +
  geom_bar(stat = "identity", na.rm = TRUE) +
  coord_flip() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(title = "Correlation mit Life_Ladder [only 10 most important]",
       x = "Variable", y = "Correlation") +
  theme_minimal() +
  theme(axis.text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))

```




```{r}
#Gini Koeffizient 

# last_year <- df %>% group_by("Country_Name") %>% 

```


